services:
  fxsrEckwerkDev:
    image: fxsrdocker/eckwerkstuttgart:0.0.3
    container_name: fxsrEckwerkStuttgartDev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eckwerk.entryPoints=websecure"
      - "traefik.http.routers.eckwerk.rule=Host(`eckwerk-dev.fxsr.de`)"
      - "traefik.http.routers.eckwerk.tls=true"
      - "traefik.http.routers.eckwerk.tls.certresolver=staging"
      - "traefik.http.services.eckwerk.loadbalancer.server.port=8083"
      - "traefik.http.services.eckwerk.loadbalancer.server.scheme=websecure"
    ports:
      - "8083:80"
    restart: unless-stopped
    networks:
      - traefik-net
