services:
  fxsrEckwerkDev:
    image: fxsrdocker/eckwerkstuttgart:0.0.3
    container_name: fxsrEckwerkStuttgartDev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eckwerkstuttgart.rule=Host(`eckwerk-dev.fxsr.de`)"
      - "traefik.http.routers.eckwerkstuttgart.entrypoints=http"
      - "traefik.http.routers.eckwerkstuttgart.tls=true"
      - "traefik.http.routers.eckwerkstuttgart.middlewares=default-headers"
      - "traefik.http.services.eckwerkstuttgart.loadbalancer.server.port=8083"
      - "traefik.http.services.eckwerkstuttgart.loadbalancer.server.scheme=http"
    ports:
      - "8083:80"
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true
