services:
  fxsrEckwerkDev:
    image: fxsrdocker/eckwerkstuttgart:0.0.3
    container_name: fxsrEckwerkStuttgartDev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eckwerkstuttgart.rule=Host(`eckwerk-dev.fxsr.de`)"
      - "traefik.http.routers.eckwerkstuttgart.entrypoints=https"
      - "traefik.http.routers.eckwerkstuttgart.tls=true"
      - "traefik.http.services.eckwerkstuttgart.loadbalancer.server.scheme=http"
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true
