services:
  fxsrEckwerkDev:
    image: fxsrdocker/eckwerkstuttgart:0.0.3
    container_name: fxsrEckwerkStuttgartDev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fxsrDockerRegistry.rule=Host(`eckwerk-dev`)"
      - "traefik.http.routers.fxsrDockerRegistry.entrypoints=https"
      - "traefik.http.routers.fxsrDockerRegistry.tls=https"
      - "traefik.http.routers.fxsrDockerRegistry.tls.certresolver=production"
      - "traefik.http.services.fxsrDockerRegistry.loadbalancer.server.port=8008"
      - "traefik.http.services.fxsrDockerRegistry.loadbalancer.server.scheme=https"
    ports:
      - 8008:80
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true
