services:
  fxsrEckwerkDev:
    image: fxsrdocker/eckwerkstuttgart:0.0.3
    container_name: eckwerkStuttgart-Dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eckwerk.entryPoints=websecure"
      - "traefik.http.routers.eckwerk.rule=Host(`eckwerk-dev.fxsr.de`)"
      - "traefik.http.routers.eckwerk.tls=true"
      - "traefik.http.routers.eckwerk.tls.certresolver=production"
    restart: unless-stopped
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
