services:
  fxsrEckwerkDev:
    image: fxsrdocker/eckwerkstuttgart:0.0.3
    container_name: fxsrEckwerkStuttgartDev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eckwerk.entrypoints=https"
      - "traefik.http.routers.eckwerk.rule=Host(`eckwerk-dev.fxsr.de`)"
      - "traefik.http.routers.eckwerk.tls=true"
      - "traefik.http.routers.middlewares.headers=default-security-headers"
      - "traefik.http.services.eckwerk.loadbalancer.server.port=8083"
      - "traefik.http.services.eckwerk.loadbalancer.server.scheme=http"
    ports:
      - "8083:80"
    restart: unless-stopped
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
