services:
  fxsrEckwerkDev:
    image: fxsrdocker/eckwerkstuttgart:0.0.3
    container_name: fxsrEckwerkStuttgartDev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eckwerkstuttgart.rule=Host(`eckwerk-dev`)"
      - "traefik.http.routers.eckwerkstuttgart.entrypoints=https"
      - "traefik.http.services.eckwerkstuttgart.loadbalancer.server.port=80"
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true
