name: Changesets

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  changesets:
    name: Create Changelog and Version Bump
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install Dependencies
      - run: yarn install
      - run: yarn changeset version


