name: Deploy Develop on FXSR Two

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Login to fxsr Container Registry'
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
      - name: 'Build Inventory Image'
        run: |
          docker build . --tag eckwerkstuttgart:latest
          docker push eckwerkstuttgart:latest
