name: Deploy Develop on fxsr Portainer

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Login to fxsr Container Registry'
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Extract version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_URI=registry.fxsr.de/eckwerkstuttgart/eckwerkstuttgart" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ${{ env.DOCKER_IMAGE_URI }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.DOCKER_IMAGE_URI }}:${{ env.IMAGE_TAG }}

  deploy:
    name: Deploy stack to Portainer
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack-name: 'eckwerkstuttgart'
          stack-definition: 'docker-compose.yml'
          image: ${{ env.DOCKER_IMAGE_URI }}:${{ env.IMAGE_TAG }}
          pull-image: true
