name: Deploy Develop on fxsr server

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Login to Docker Registry'
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Extract version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Inventory Image
        run: |
          docker build . --tag fxsrdocker/eckwerkstuttgart:${{ env.VERSION }}
          docker push fxsrdocker/eckwerkstuttgart:${{ env.VERSION }}

  deploy:
    name: Deploy on Portainer
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on fxsr server portainer
        uses: nevcodia/portainer-stack-deployment@v2.19.3
        with:
          url: https://portainer.fxsr.de
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          environment_id: 0
          stack_name: portainer-stack-deployment-test
          stack_file_path: docker-compose.yml
