name: Deploy Develop on Azure

on:
  push:
    branches: [develop]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_30E71780CC3E416DAA1BB0D737C603DC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_46DFB070BCEC4D858D6239F9149DE101 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_42A702832DA64A3C8909178131169572 }}

      - name: Build Docker image
        run: |
          docker build -t fxsreckwerkstuttgartreg.azurecr.io/eckwerkstuttgart/eckwerkstuttgart:latest .

      - name: Push Docker image to Azure Container Registry
        run: |
          docker push fxsre ggckwerkstuttgartreg.azurecr.io/eckwerkstuttgart/eckwrkstuttgart:latest
