name: Deploy Develop on fxsr server

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Login to Docker Registry'
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Extract version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Inventory Image
        run: |
          docker build . --tag fxsrdocker/eckwerkstuttgart:${{ env.VERSION }}
          docker push fxsrdocker/eckwerkstuttgart:${{ env.VERSION }}

  deploy:
    name: Deploy on Portainer
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Restore docker-compose.yml from cache
        uses: actions/cache@v3
        with:
          path: docker-compose.yml
          key: ${{ runner.os }}-docker-compose-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-compose-

      - name: Get changed Docker Compose files
        run: |
          git diff --name-only HEAD^ HEAD | grep 'docker-compose.yml' > changed_files.txt

      - name: Deploy on fxsr server portainer
        uses: BramKelchtermans/portainer-deploy-action@beta-0.2
        with:
          portainer_url: ${{ secrets.PORTAINER_URL }}
          portainer_api_key: ${{ secrets.PORTAINER_API_KEY }}
          changed_files_path: 'changed_files.txt'
